{{- /*
If the used envFroms secret
*/ -}}
{{- if .Values.envFroms.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    app: {{ template "application.name" . }}
    chart: {{ template "application.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- range $key, $value := .Values.envFroms.env }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
