apiVersion: v1
data:
  tls.crt: ""
  tls.key: ""
kind: Secret
metadata:
  name: domain-frontend-tls
  namespace: default
type: kubernetes.io/tls

# https://shocksolution.com/2018/12/14/creating-kubernetes-secrets-using-tls-ssl-as-an-example/
